### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by xiangxm** [zaleGZL/simple-weather#2]
hi, 代码下载下来编译报错npm install 

➜  simple-weather git:(master) npm install             
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 5.277s

**Comment by zaleGZL** [comment]
我使用的是 yarn 包管理工具，你试试 Yarn
